### ISSUE TITLE
Übung für Start

### ISSUE THREAD

**Issue by florianhartig** [TheoreticalEcology/AdvancedRegressionModels#23]
Basierend auf airquality

a) summary + str
b) chr oder numeric to faktor umwandeln (airquality)
c) skalieren, transformieren, neue Variable im DF erstellen
d) subsetted, NAs remove, complete.cases
e) plotten (numeric  gegen numeric, numeric gegen factor, hist), pairs
f) correlation?

**Comment by MaximilianPi** [comment]
8a0fceff2daf4b1b8c0c92513e33ddd8993043a2
